---
- name: Install required packages
  dnf:
    name:
      - unzip
      - python3.12
      - kernel-devel
      - kernel-headers
      - gcc
      - gcc-c++
      - elfutils
      - elfutils-devel
      - make
    state: latest
